import React, { useState, useEffect } from 'react';
import { NavLink, useNavigate, useLocation } from 'react-router-dom';
import { LayoutDashboard, Files, ClipboardList, ChartNoAxesCombined, Users, ShieldCheck, Settings2, Bell, Search, ChevronDown, ArrowUpRight, PanelLeftClose, X, Sun, Moon, LogOut, CheckCheck, Menu } from 'lucide-react';
import { api, roleNames } from '../lib/api';
import { IconBtn, Btn, Empty } from './common';

const logo = 'https://customer-assets-m6fa6gv7.emergentagent.net/job_283eb062-afd4-459d-9507-f84f42e09f9a/artifacts/mzkw1aog_image%201.png';
const menus = [{ to: '/', name: 'Dashboard', icon: LayoutDashboard, roles: ['administrator','supervisor','director','employee'] }, { to: '/ketentuan', name: 'Ketentuan', icon: Files, roles: ['administrator','supervisor','director','employee'] }, { to: '/kuis', name: 'Manajemen Kuis', employeeName: 'Kuis Saya', icon: ClipboardList, roles: ['administrator','supervisor','director','employee'] }, { to: '/monitoring', name: 'Monitoring & Laporan', icon: ChartNoAxesCombined, roles: ['administrator','supervisor','director'] }, { to: '/hasil', name: 'Hasil Kuis', icon: ChartNoAxesCombined, roles: ['employee'] }];
const adminMenus = [{ to: '/pengguna', name: 'Manajemen Pengguna', icon: Users, roles: ['administrator','supervisor'] }, { to: '/audit', name: 'Audit Trail', icon: ShieldCheck, roles: ['administrator','supervisor','director'] }, { to: '/pengaturan', name: 'Pengaturan', icon: Settings2, roles: ['administrator'] }];
export const Layout = ({ user, onSwitch, onLogout, children }) => {
  const [mobile, setMobile] = useState(false), [notices, setNotices] = useState([]), [showNotices, setShowNotices] = useState(false), [search, setSearch] = useState(''), [dark, setDark] = useState(localStorage.getItem('cms-dark') === 'true');
  const navigate = useNavigate(), location = useLocation();
  useEffect(() => { api.get('/notifications').then(r => setNotices(r.data)).catch(()=>{}); setMobile(false); }, [user, location.pathname]);
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('cms-dark', dark); }, [dark]);
  const read = async n => { await api.post(`/notifications/${n.id}/read`); setNotices(old => old.map(v=>v.id===n.id?{...v,read_by:[...v.read_by,user.id]}:v)); setShowNotices(false); navigate(n.link); };
  const renderNav = (items) => items.filter(m=>m.roles.includes(user.role)).map(({to,name,employeeName,icon:Icon})=><NavLink end={to === '/'} key={to} data-testid={`nav-${to === '/' ? 'dashboard' : to.slice(1)}`} to={to} className={({isActive})=>`nav-item ${isActive?'nav-active':''}`}><Icon size={19}/><span>{user.role==='employee' && employeeName ? employeeName : name}</span>{to==='/'&&<span className="nav-dot"/>}</NavLink>);
  return <div className="app-shell">
    {mobile && <button data-testid="sidebar-backdrop" className="sidebar-backdrop" aria-label="Tutup menu" onClick={()=>setMobile(false)}/>}
    <aside className={`sidebar ${mobile?'sidebar-open':''}`}>
      <NavLink to="/" className="brand" data-testid="brand-home"><img src={logo} alt="Logo Bali Dwipa Jaya" data-testid="logo-bank-bpd-bali"/><div><strong>BALI DWIPA JAYA<span>COMPLIANCE MANAGEMENT</span></strong></div></NavLink>
      <div className="workspace-label"><span className="workspace-icon"><ShieldCheck size={19}/></span><div>Ruang Kepatuhan<small>Bank BPD Bali</small></div><ChevronDown size={14}/></div>
      <div className="nav-caption">MENU UTAMA</div><nav>{renderNav(menus)}</nav>
      {adminMenus.some(m=>m.roles.includes(user.role)) && <><div className="nav-caption second-caption">ADMINISTRASI</div><nav>{renderNav(adminMenus)}</nav></>}
      <div className="sidebar-bottom"><div className="compliance-note"><ShieldCheck size={24}/><h3>Integritas dalam<br/>setiap langkah.</h3><p>Bersama membangun<br/>budaya patuh.</p><span className="gold-line"/></div><div className="sidebar-version"><span className="live-dot"/> CMS v1.0 <span>RUANG DEMO</span></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="topbar-left"><IconBtn label="Buka menu" data-testid="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu size={19}/></IconBtn><div className="breadcrumb">Workspace <span>/</span> <strong>Kepatuhan</strong></div><form className="global-search" onSubmit={e=>{e.preventDefault();navigate('/ketentuan?q='+encodeURIComponent(search));}}><Search size={17}/><input data-testid="global-search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari ketentuan atau nomor dokumen..."/><kbd>↵</kbd></form></div><div className="topbar-right"><div className="role-control"><span className="live-dot"/><select data-testid="role-switcher-dropdown" aria-label="Peran demo" value={user.role} onChange={e=>onSwitch(e.target.value)}>{Object.entries(roleNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><IconBtn data-testid="theme-toggle-button" label={dark?'Mode terang':'Mode gelap'} onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={18}/>}</IconBtn><div className="notice-wrapper"><IconBtn data-testid="notification-toggle" label="Notifikasi" onClick={()=>setShowNotices(!showNotices)}><Bell size={19}/>{notices.some(n=>!n.read_by.includes(user.id))&&<span className="notification-dot"/>}</IconBtn>{showNotices&&<div className="notification-panel" data-testid="notification-panel"><div className="section-head"><h2>Notifikasi</h2><IconBtn label="Tutup notifikasi" data-testid="notification-close" onClick={()=>setShowNotices(false)}><X size={16}/></IconBtn></div>{notices.length?notices.map(n=><button data-testid={`notification-${n.id}`} key={n.id} onClick={()=>read(n)} className={`notification-item ${n.read_by.includes(user.id)?'read':''}`}><span className="notice-icon"><Bell size={17}/></span><div><strong>{n.title}</strong><p>{n.detail}</p></div></button>):<Empty text="Tidak ada notifikasi baru."/>}</div>}</div><span className="topbar-divider"/><div className="user-identity"><span className="avatar">{user.name.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><div><strong data-testid="current-user-name">{user.name}</strong><small>{roleNames[user.role]} SISDUR</small></div></div><IconBtn label="Keluar" data-testid="logout-button" onClick={onLogout}><LogOut size={17}/></IconBtn></div></header><main className="main-content" key={location.pathname}>{children}</main><footer className="page-footer"><span>© 2026 Bank BPD Bali. Seluruh hak dilindungi.</span><span><span className="live-dot"/> Lingkungan demo · Data contoh</span></footer></div>
  </div>;
};