import React,{useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Plus,Eye,LockKeyhole,LockKeyholeOpen,Save,ShieldCheck,Check,ArrowUpRight,Search} from 'lucide-react';
import {toast} from 'sonner';
import {api,dateLabel,units,roleNames} from '../lib/api';
import {PageHead,Btn,IconBtn,Loading,Empty,SearchBox,Modal,Field,Badge} from '../components/common';
import {ResultView} from './TakeQuiz';

export const UsersPage=({user})=>{
 const [users,setUsers]=useState(null),[q,setQ]=useState(''),[role,setRole]=useState(''),[detail,setDetail]=useState(null),[form,setForm]=useState(null),[busy,setBusy]=useState(false);
 const load=()=>api.get('/users').then(r=>setUsers(r.data)).catch(()=>{});
 useEffect(()=>{load();},[user]);
 const view=async id=>{try{const {data}=await api.get(`/users/${id}/detail`);setDetail(data);}catch{}};
 const toggle=async id=>{setBusy(true);try{await api.post(`/users/${id}/toggle`);load();toast.success('Status pengguna berhasil diperbarui.');}catch{}finally{setBusy(false);}};
 const save=async e=>{e.preventDefault();setBusy(true);try{await api.post('/users',form);setForm(null);load();toast.success('Pengguna berhasil ditambahkan.');}catch{}finally{setBusy(false);}};
 if(!users)return <Loading/>;
 const filtered=users.filter(u=>(!role||u.role===role)&&`${u.name} ${u.unit}`.toLowerCase().includes(q.toLowerCase()));
 return <><PageHead eyebrow="ADMINISTRASI" title="Manajemen Pengguna" subtitle="Kelola data karyawan, peran, dan akses ke sistem kepatuhan.">{user.role==='administrator'&&<Btn data-testid="user-create" onClick={()=>setForm({name:'',email:'',nrk:'',unit:units[0],position:'Officer',role:'employee'})}><Plus size={16}/>Tambah Pengguna</Btn>}</PageHead><div className="toolbar"><SearchBox id="user-search" value={q} onChange={setQ} placeholder="Cari nama karyawan atau unit..."/><select data-testid="user-role-filter" value={role} onChange={e=>setRole(e.target.value)}><option value="">Semua Peran</option>{Object.entries(roleNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="content-table"><div className="table-scroll"><table className="data-table" data-testid="users-table"><thead><tr>{['KARYAWAN','NRK','UNIT KERJA','JABATAN','PERAN','STATUS','AKSI'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.map(u=><tr key={u.id} data-testid={`user-row-${u.id}`}><td><div className="doc-title-cell"><span className="avatar">{u.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><strong>{u.name}</strong><small>{u.email}</small></div></div></td><td className="muted">{u.nrk}</td><td>{u.unit}</td><td>{u.position}</td><td>{roleNames[u.role]}</td><td><Badge id={`user-status-${u.id}`} status={u.active?'Aktif':'Diblokir'}/></td><td>{user.role==='administrator'&&<div className="table-actions"><IconBtn data-testid={`user-view-${u.id}`} label="Lihat detail pribadi" onClick={()=>view(u.id)}><Eye size={16}/></IconBtn>{!u.id.startsWith('demo-')&&<IconBtn disabled={busy} data-testid={`user-toggle-${u.id}`} label={u.active?'Blokir pengguna':'Buka blokir'} onClick={()=>toggle(u.id)}>{u.active?<LockKeyhole size={16}/>:<LockKeyholeOpen size={16}/>}</IconBtn>}</div>}</td></tr>)}</tbody></table></div>{!filtered.length&&<Empty/>}<div className="table-bottom"><span data-testid="user-count">{filtered.length} pengguna</span><span><ShieldCheck size={12} style={{display:'inline',marginRight:5}}/>Data pribadi dilindungi</span></div></div>
 <Modal title="Detail Pengguna" open={!!detail} onClose={()=>setDetail(null)}>{detail&&<><div className="details-meta">{[['Nama',detail.name],['NRK',detail.nrk],['Email',detail.email],['Unit Kerja',detail.unit],['Jabatan',detail.position],['Peran',roleNames[detail.role]]].map(([l,v])=><div key={l} data-testid={`user-detail-${l.toLowerCase().replace(' ','-')}`}><small>{l}</small>{v}</div>)}</div><div className="info-note">Akses detail pribadi ini telah tercatat dalam audit trail.</div></>}</Modal>
 <Modal title="Tambah Pengguna" open={!!form} onClose={()=>setForm(null)}>{form&&<form onSubmit={save}><div className="form-grid">{[['name','Nama Lengkap'],['nrk','NRK'],['email','Email']].map(([k,l])=><Field key={k} label={`${l} *`} className={k==='email'?'field-full':''}><input data-testid={`user-${k}-input`} required minLength={3} type={k==='email'?'email':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}<Field label="Unit Kerja"><select data-testid="user-unit-input" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}>{units.map(u=><option key={u}>{u}</option>)}</select></Field><Field label="Jabatan"><select data-testid="user-position-input" value={form.position} onChange={e=>setForm({...form,position:e.target.value})}><option>Officer</option><option>Kepala Unit</option></select></Field><Field label="Peran"><select data-testid="user-role-input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="employee">Karyawan</option><option value="supervisor">Supervisor</option><option value="director">Direksi</option></select></Field></div><div className="form-actions"><Btn type="button" secondary data-testid="user-cancel" onClick={()=>setForm(null)}>Batal</Btn><Btn type="submit" disabled={busy} data-testid="user-save">Simpan Pengguna</Btn></div></form>}</Modal></>;
};

export const AuditPage=()=>{
 const [rows,setRows]=useState(null),[q,setQ]=useState(''),[module,setModule]=useState('');
 useEffect(()=>{api.get('/audit').then(r=>setRows(r.data)).catch(()=>{});},[]);
 if(!rows)return <Loading/>;
 const filtered=rows.filter(r=>(!module||r.module===module)&&`${r.user_name} ${r.action} ${r.detail}`.toLowerCase().includes(q.toLowerCase()));
 return <><PageHead eyebrow="TATA KELOLA & PENGAWASAN" title="Audit Trail" subtitle="Jejak aktivitas pengguna untuk mendukung pengawasan dan akuntabilitas."/><div className="toolbar"><SearchBox id="audit-search" value={q} onChange={setQ} placeholder="Cari pengguna, tindakan, atau aktivitas..."/><select data-testid="audit-module-filter" value={module} onChange={e=>setModule(e.target.value)}><option value="">Semua Modul</option>{[...new Set(rows.map(r=>r.module))].map(m=><option key={m}>{m}</option>)}</select></div><div className="content-table"><div className="table-scroll"><table className="data-table" data-testid="audit-table"><thead><tr>{['WAKTU AKSES','PENGGUNA','MODUL','TINDAKAN','DETAIL AKTIVITAS','IP AKSES'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} data-testid={`audit-row-${r.id}`}><td><span>{dateLabel(r.timestamp)}</span><small className="muted" style={{display:'block',marginTop:4}}>{new Date(r.timestamp).toLocaleTimeString('id-ID')}</small></td><td>{r.user_name}</td><td>{r.module}</td><td><span className="audit-action">{r.action}</span></td><td style={{whiteSpace:'normal',minWidth:230,maxWidth:380}}>{r.detail}</td><td className="muted" style={{fontFamily:'IBM Plex Mono'}}>{r.ip}</td></tr>)}</tbody></table></div>{!filtered.length&&<Empty/>}<div className="table-bottom"><span data-testid="audit-count">{filtered.length} aktivitas terakhir</span><span>Hanya baca · Tidak dapat diubah melalui aplikasi</span></div></div></>;
};

export const SettingsPage=()=>{
 const [settings,setSettings]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{api.get('/settings').then(r=>setSettings(r.data)).catch(()=>{});},[]);
 const save=async e=>{e.preventDefault();setBusy(true);try{const {data}=await api.put('/settings',settings);setSettings(data);window.dispatchEvent(new CustomEvent('cms-settings-updated',{detail:data}));toast.success('Parameter aplikasi berhasil disimpan.');}catch{}finally{setBusy(false);}};
 if(!settings)return <Loading/>;
 return <form onSubmit={save}><PageHead eyebrow="ADMINISTRASI" title="Pengaturan" subtitle="Parameter evaluasi dan keamanan sesi pengguna."><Btn data-testid="settings-save" type="submit" disabled={busy}><Save size={15}/>{busy?'Menyimpan...':'Simpan Perubahan'}</Btn></PageHead><section className="settings-section"><div><h2>Parameter Kuis</h2><p>Nilai bawaan untuk kuis baru. Kuis yang sudah dibuat tidak berubah.</p></div><div className="settings-form"><Field label="Passing Grade Bawaan"><input data-testid="settings-passing-grade" required type="number" min={1} max={100} value={settings.passing_grade} onChange={e=>setSettings({...settings,passing_grade:Number(e.target.value)})}/></Field><Field label="Durasi Kuis Bawaan (menit)"><input data-testid="settings-duration" required type="number" min={1} max={180} value={settings.quiz_duration} onChange={e=>setSettings({...settings,quiz_duration:Number(e.target.value)})}/></Field></div></section><section className="settings-section"><div><h2>Keamanan Sesi</h2><p>Sesi berakhir setelah tidak ada aktivitas permintaan data selama batas waktu yang ditetapkan.</p></div><div className="settings-form"><Field label="Idle Timeout (detik)"><input data-testid="settings-idle-timeout" required type="number" min={60} max={3600} value={settings.idle_timeout} onChange={e=>setSettings({...settings,idle_timeout:Number(e.target.value)})}/></Field></div></section><section className="settings-section"><div><h2>Koneksi Sistem</h2><p>Status layanan aplikasi dan koneksi sistem internal bank.</p></div><div>{[['Penyimpanan Data','Data ketentuan, kuis, dan hasil evaluasi','Terhubung'],['Notifikasi Dalam Aplikasi','Penugasan, persetujuan, dan pengingat','Aktif'],['Active Directory / SSO','Autentikasi karyawan bank','Belum dikonfigurasi'],['Mail Server Bank','Email dan OTP','Belum dikonfigurasi'],['SIM SDM','Sinkronisasi data karyawan','Belum dikonfigurasi']].map(([l,d,s],i)=><div className="connection-row" key={l}><div><strong>{l}</strong><small>{d}</small></div><Badge id={`connection-status-${i}`} status={s}/></div>)}</div></section></form>;
};

export const ResultsPage=()=>{
 const [results,setResults]=useState(null),[detail,setDetail]=useState(null),[q,setQ]=useState(''); const navigate=useNavigate();
 useEffect(()=>{api.get('/results').then(r=>setResults(r.data)).catch(()=>{});},[]);
 if(!results)return <Loading/>;
 if(detail)return <ResultView result={detail} onDone={()=>{setDetail(null);navigate('/kuis');}}/>;
 const filtered=results.filter(r=>r.quiz_title.toLowerCase().includes(q.toLowerCase()));
 return <><PageHead eyebrow="EVALUASI PERSONAL" title="Hasil Kuis" subtitle="Riwayat nilai dan perkembangan pemahaman ketentuan Anda."/><div className="toolbar"><SearchBox id="results-search" value={q} onChange={setQ} placeholder="Cari judul kuis..."/></div><div className="content-table"><div className="table-scroll"><table className="data-table" data-testid="results-table"><thead><tr>{['KUIS','TANGGAL PENGUMPULAN','NILAI','PASSING GRADE','STATUS','AKSI'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} data-testid={`result-row-${r.id}`}><td><strong>{r.quiz_title}</strong></td><td>{dateLabel(r.submitted_at)}</td><td>{r.score} / 100</td><td>{r.passing_grade}</td><td><Badge id={`result-status-${r.id}`} status={r.status}/></td><td><Btn secondary data-testid={`result-view-${r.id}`} onClick={()=>setDetail(r)}>Detail & Feedback<ArrowUpRight size={14}/></Btn></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty text="Belum ada hasil kuis. Selesaikan kuis pertama Anda."/>}</div></>;
};