import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Files, ClipboardCheck, Users, BadgeCheck, ArrowUpRight, ArrowRight, Download, Plus, CalendarDays, Building2, ChevronRight, CircleCheck, FileText, Clock3, Sparkles, ShieldCheck } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, PieChart, Pie, Cell } from 'recharts';
import { ChartContainer as ResponsiveContainer } from '../components/ChartContainer';
import { api, units, download, dateLabel } from '../lib/api';
import { PageHead, Btn, Stat, SectionHead, Loading, ArrowLink, Badge } from '../components/common';

export const PeriodFilter = ({value,onChange,id='period-filter'}) => <div className="select-wrap"><CalendarDays size={16}/><select data-testid={id} value={value} onChange={e=>onChange(e.target.value)}><option value="2026">Tahun 2026</option><option value="2026-Q1">Triwulan I 2026</option><option value="2026-Q2">Triwulan II 2026</option><option value="2026-Q3">Triwulan III 2026</option><option value="2026-Q4">Triwulan IV 2026</option><option value="2026-S1">Semester I 2026</option><option value="2026-S2">Semester II 2026</option><option value="all">Semua periode</option></select></div>;
export const UnitFilter = ({value,onChange,id='unit-filter'}) => <div className="select-wrap"><Building2 size={16}/><select data-testid={id} value={value} onChange={e=>onChange(e.target.value)}><option value="">Semua Unit Kerja</option>{units.map(u=><option key={u}>{u}</option>)}</select></div>;
export default function Dashboard({user}){
  const [data,setData]=useState(null),[period,setPeriod]=useState('2026'),[unit,setUnit]=useState('');
  const navigate=useNavigate();
  useEffect(()=>{api.get('/dashboard',{params:{period,unit}}).then(r=>setData(r.data)).catch(()=>{});},[period,unit,user]);
  if(!data)return <Loading/>;
  const m=data.metrics; const employee=user.role==='employee';
  const pie=[{name:'Sudah mengikuti',value:m.completed,color:'#16805d'},{name:'Belum mengikuti',value:m.pending,color:'#ebbf60'}];
  return <>
    <PageHead eyebrow="OVERVIEW" title="Dashboard Kepatuhan" subtitle={`Selamat datang, ${user.name}. Mari tumbuhkan budaya kepatuhan bersama.`}>{!employee&&<Btn secondary data-testid="dashboard-export" onClick={()=>download(`/reports/export?period=${period}&unit=${encodeURIComponent(unit)}`,'laporan-kepatuhan.csv')}><Download size={16}/>Ekspor Laporan</Btn>}{user.role==='administrator'&&<Btn data-testid="dashboard-create-quiz" onClick={()=>navigate('/kuis?create=1')}><Plus size={17}/>Buat Kuis</Btn>}{employee&&<Btn data-testid="dashboard-my-quizzes" onClick={()=>navigate('/kuis')}>Kuis Saya<ArrowUpRight size={17}/></Btn>}</PageHead>
    <div className="dashboard-filter"><div className="overview-tab"><span className="live-dot"/> Ringkasan Kepatuhan <span className="tiny-tag">{employee?'Personal':'Bankwide'}</span></div><div className="filter-group"><PeriodFilter value={period} onChange={setPeriod}/>{!employee&&<UnitFilter value={unit} onChange={setUnit}/>}</div></div>
    <div className="stats-grid"><Stat id="documents" label="Total Ketentuan Aktif" value={m.documents} icon={Files} detail={<><span className="mini-dot green"/>{m.internal} Internal <span className="detail-divider"/> <span className="mini-dot blue"/>{m.external} Eksternal</>}/><Stat id="quizzes" label="Kuis Berlangsung" value={m.active_quizzes} tone="blue" icon={ClipboardCheck} detail={<><span className="sub-badge">Aktif</span> {m.employees} karyawan terdaftar</>}/><Stat id="participation" label="Tingkat Partisipasi" value={`${m.participation}%`} icon={Users} detail={<><span className="trend-mark"><ArrowUpRight size={13}/>{m.completed}</span> dari {m.assigned} penugasan selesai</>}/><Stat id="pass-rate" label="Tingkat Kelulusan" value={`${m.pass_rate}%`} tone="gold" icon={BadgeCheck} detail={<><span className="trend-mark"><CircleCheck size={13}/>{m.passed}</span> hasil kuis di atas passing grade</>}/></div>
    <div className="chart-grid"><section className="chart-panel"><SectionHead title="Tren Kepatuhan" subtitle="Perkembangan partisipasi dan pemahaman karyawan"><span className="chart-time">6 bulan terakhir</span></SectionHead><div className="chart-legend"><span><i style={{background:'#16805d'}}/>Partisipasi kuis</span><span><i style={{background:'#d6ab54'}}/>Rata-rata nilai</span></div><div className="trend-chart" data-testid="compliance-trend-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trend} margin={{top:12,right:15,left:-24,bottom:0}}><defs><linearGradient id="participationFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#16805d" stopOpacity={.18}/><stop offset="100%" stopColor="#16805d" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e9eeeb"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:'#85908b',fontSize:12}} dy={10}/><YAxis domain={[0,100]} ticks={[0,25,50,75,100]} axisLine={false} tickLine={false} tick={{fill:'#85908b',fontSize:11}} tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={{border:'1px solid #e4eae7',borderRadius:8,fontSize:12}} formatter={(v,n)=>[`${v}${n==='Partisipasi kuis'?'%':''}`,n]}/><Area type="monotone" dataKey="participation" name="Partisipasi kuis" stroke="#16805d" strokeWidth={2.6} fill="url(#participationFill)" dot={{r:3,fill:'#fff',strokeWidth:2}}/><Area type="monotone" dataKey="score" name="Rata-rata nilai" stroke="#d6ab54" strokeWidth={2} strokeDasharray="5 4" fill="transparent" dot={false}/></AreaChart></ResponsiveContainer></div><div className="chart-footnote"><ShieldCheck size={14}/><span>Rata-rata nilai periode ini</span><strong data-testid="average-score">{m.average}<small> / 100</small></strong></div></section>
    <section className="participation-panel"><SectionHead title="Status Partisipasi" subtitle="Penyelesaian seluruh penugasan kuis"/><div className="donut-chart" data-testid="participation-donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pie.some(p=>p.value)?pie:[{name:'Belum ada penugasan',value:1,color:'#edf0ee'}]} dataKey="value" innerRadius="72%" outerRadius="90%" startAngle={90} endAngle={-270} paddingAngle={m.pending&&m.completed?3:0} stroke="none">{(pie.some(p=>p.value)?pie:[{color:'#edf0ee'}]).map((p,i)=><Cell key={i} fill={p.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{m.participation}<span>%</span></strong><small>Partisipasi keseluruhan</small></div></div><div className="donut-legend">{pie.map((p,i)=><div key={p.name}><span><i style={{background:p.color}}/>{p.name}</span><strong data-testid={`participation-count-${i}`}>{p.value}</strong></div>)}</div><div className="participation-note"><Users size={15}/>{m.employees} karyawan dalam periode ini</div></section></div>
    <div className="bottom-grid"><section className="unit-section"><SectionHead title={employee?'Ketentuan Terbaru':'Performa Unit Kerja'} subtitle={employee?'Materi kepatuhan yang telah dipublikasikan':'Partisipasi dan hasil evaluasi per unit kerja'}><ArrowLink data-testid="dashboard-view-units" onClick={()=>navigate(employee?'/ketentuan':'/monitoring')}>Lihat semua</ArrowLink></SectionHead>{employee?<div>{data.recent_documents.map(d=><button className="recent-doc" key={d.id} data-testid={`recent-doc-${d.id}`} onClick={()=>navigate('/ketentuan?q='+encodeURIComponent(d.title))}><FileText size={20}/><div><strong>{d.title}</strong><small>{d.number}</small></div><ChevronRight size={16}/></button>)}</div>:<div className="table-scroll"><table className="data-table compact" data-testid="unit-performance-table"><thead><tr><th>UNIT KERJA</th><th>PARTISIPASI</th><th>RATA-RATA NILAI</th><th>STATUS</th></tr></thead><tbody>{data.units.slice(0,5).map((u,i)=><tr key={u.unit} data-testid={`unit-performance-${i}`}><td><div className="unit-name"><span className="unit-icon"><Building2 size={15}/></span>{u.unit}</div></td><td><div className="table-progress"><div><i style={{width:`${u.participation}%`}}/></div><span>{u.participation}%</span></div></td><td><strong>{u.average}</strong><span className="muted"> / 100</span></td><td><span className={`status ${u.average>=75?'status-passed':'status-pending'}`}><span/>{u.average>=75?'Baik':'Perlu perhatian'}</span></td></tr>)}</tbody></table></div>}</section><section className="attention-section"><SectionHead title="Perlu Perhatian" subtitle="Tindak lanjut untuk kepatuhan yang lebih baik"/><div className="attention-list">{!employee&&<><button className="attention-item" data-testid="attention-documents" onClick={()=>navigate('/ketentuan?status=pending')}><span className="attention-icon amber"><Files size={19}/></span><div><strong>{data.tasks.documents} ketentuan menunggu review</strong><small>Periksa dan tinjau dokumen baru</small></div><ChevronRight size={16}/></button><button className="attention-item" data-testid="attention-essays" onClick={()=>navigate('/monitoring?tab=essay')}><span className="attention-icon blue"><ClipboardCheck size={19}/></span><div><strong>{data.tasks.essays} esai belum dinilai</strong><small>Lengkapi hasil evaluasi karyawan</small></div><ChevronRight size={16}/></button></>}<button className="attention-item" data-testid="attention-quizzes" onClick={()=>navigate('/kuis')}><span className="attention-icon green"><Clock3 size={19}/></span><div><strong>{m.active_quizzes} kuis sedang berlangsung</strong><small>Pantau penyelesaian sebelum tenggat</small></div><ChevronRight size={16}/></button></div><div className="integrity-strip"><ShieldCheck size={20}/><p>Kepatuhan hari ini.<br/><strong>Kepercayaan untuk masa depan.</strong></p></div></section></div>
  </>;
}