import React, {useEffect,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {Plus,FileText,Download,Eye,Pencil,Trash2,UploadCloud,Send,Check,X,Files,Building2} from 'lucide-react';
import {toast} from 'sonner';
import {api,download,dateLabel,units} from '../lib/api';
import {PageHead,Btn,IconBtn,Modal,Field,SearchBox,Badge,Empty,Loading} from '../components/common';

const blank = {title:'',number:'',category:'Internal',unit:units[0],description:'',version:'1.0'};
export default function Documents({user}){
 const [params]=useSearchParams();const [docs,setDocs]=useState(null),[q,setQ]=useState(params.get('q')||''),[category,setCategory]=useState(''),[status,setStatus]=useState(params.get('status')||''),[editing,setEditing]=useState(null),[detail,setDetail]=useState(null),[remove,setRemove]=useState(null),[reject,setReject]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 const admin=user.role==='administrator',supervisor=user.role==='supervisor';
 const load=()=>api.get('/documents').then(r=>setDocs(r.data)).catch(()=>{});
 useEffect(()=>{load();},[user]);
 useEffect(()=>{setQ(params.get('q')||'');setStatus(params.get('status')||'');},[params]);
 const action=async(doc,action,reason='')=>{setBusy(true);try{await api.post(`/documents/${doc.id}/action`,{action,reason});toast.success(action==='approve'?'Ketentuan disetujui dan dipublikasikan.':action==='submit'?'Ketentuan diajukan untuk review.':'Ketentuan ditolak dengan catatan.');setDetail(null);setReject(null);load();}catch{}finally{setBusy(false);}};
 const destroy=async()=>{setBusy(true);try{await api.delete(`/documents/${remove.id}`);toast.success('Draf ketentuan dihapus.');setRemove(null);load();}catch{}finally{setBusy(false);}};
 if(!docs)return <Loading/>;
 const filtered=docs.filter(d=>(!category||d.category===category)&&(!status||d.status===status)&&`${d.title} ${d.number}`.toLowerCase().includes(q.toLowerCase()));
 const tabs=[['','Semua Ketentuan'],['published','Dipublikasikan'],...(admin||supervisor?[['pending','Menunggu Review'],['draft','Draf'],['rejected','Ditolak']]:[])];
 return <><PageHead eyebrow="DOKUMEN & REGULASI" title="Ketentuan" subtitle="Kelola ketentuan internal dan eksternal dalam satu repositori terpusat.">{admin&&<Btn data-testid="document-create" onClick={()=>setEditing({...blank})}><Plus size={16}/>Tambah Ketentuan</Btn>}</PageHead>
 <div className="tab-bar">{tabs.map(([v,label])=><button data-testid={`document-tab-${v||'all'}`} className={status===v?'active':''} onClick={()=>setStatus(v)} key={v}>{label}<span>{docs.filter(d=>!v||d.status===v).length}</span></button>)}</div>
 <div className="toolbar"><div><SearchBox id="document-search" value={q} onChange={setQ} placeholder="Cari judul atau nomor ketentuan..."/></div><div><select data-testid="document-category-filter" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Semua Kategori</option><option>Internal</option><option>Eksternal</option></select><span className="muted" data-testid="document-count">{filtered.length} dokumen</span></div></div>
 <div className="content-table"><div className="table-scroll"><table className="data-table" data-testid="documents-table"><thead><tr><th>KETENTUAN</th><th>KATEGORI</th><th>UNIT PEMILIK</th><th>TANGGAL</th><th>STATUS</th><th>AKSI</th></tr></thead><tbody>{filtered.map(d=><tr key={d.id} data-testid={`document-row-${d.id}`}><td><div className="doc-title-cell"><span className="file-icon"><FileText size={20}/></span><div><strong>{d.title}</strong><small>{d.number}</small></div></div></td><td><Badge status={d.category} id={`doc-category-${d.id}`}/></td><td>{d.unit}</td><td>{dateLabel(d.created_at)}</td><td><Badge status={d.status} id={`doc-status-${d.id}`}/></td><td><div className="table-actions"><IconBtn label="Lihat ketentuan" data-testid={`document-view-${d.id}`} onClick={()=>setDetail(d)}><Eye size={16}/></IconBtn>{(d.filename||d.sample)&&<IconBtn label="Unduh dokumen" data-testid={`document-download-${d.id}`} onClick={()=>download(`/documents/${d.id}/download`,d.filename||`${d.title}-contoh.txt`).catch(()=>{})}><Download size={16}/></IconBtn>}{admin&&['draft','rejected'].includes(d.status)&&<><IconBtn label="Edit ketentuan" data-testid={`document-edit-${d.id}`} onClick={()=>setEditing(d)}><Pencil size={15}/></IconBtn><IconBtn label="Hapus draf" data-testid={`document-delete-${d.id}`} onClick={()=>setRemove(d)}><Trash2 size={15}/></IconBtn></>}{supervisor&&d.status==='pending'&&<Btn secondary data-testid={`document-review-${d.id}`} onClick={()=>setDetail(d)}>Review</Btn>}</div></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty text="Tidak ada ketentuan yang sesuai dengan pencarian."/>}<div className="table-bottom"><span data-testid="document-table-summary">Menampilkan {filtered.length} dari {docs.length} ketentuan</span><span>Repositori Ketentuan</span></div></div>
 {editing&&<DocumentForm initial={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);load();}}/>}
 <Modal title={detail?.title} open={!!detail} onClose={()=>setDetail(null)} wide>{detail&&<><div className="details-meta"><div><small>Nomor Ketentuan</small>{detail.number}</div><div><small>Status</small><Badge status={detail.status} id="document-detail-status"/></div><div><small>Unit Pemilik</small>{detail.unit}</div><div><small>Kategori / Versi</small>{detail.category} / v{detail.version}</div></div><p className="detail-description" data-testid="document-description">{detail.description||'Tidak ada ringkasan ketentuan.'}</p>{detail.review_note&&<div className="info-note danger-note" data-testid="document-review-note">Catatan supervisor: {detail.review_note}</div>}{detail.sample&&<div className="info-note">Dokumen contoh untuk ruang demo, bukan ketentuan resmi bank.</div>}<div className="form-actions">{(detail.filename||detail.sample)&&<Btn secondary data-testid="document-detail-download" onClick={()=>download(`/documents/${detail.id}/download`,detail.filename||`${detail.title}-contoh.txt`).catch(()=>{})}><Download size={16}/>Unduh {detail.sample&&!detail.filename?'Materi Contoh':'Dokumen'}</Btn>}{admin&&['draft','rejected'].includes(detail.status)&&<Btn disabled={busy} data-testid="document-submit-review" onClick={()=>action(detail,'submit')}><Send size={15}/>Ajukan Review</Btn>}{supervisor&&detail.status==='pending'&&<><Btn secondary disabled={busy} data-testid="document-reject" onClick={()=>{setReject(detail);setDetail(null);setReason('');}}><X size={15}/>Tolak</Btn><Btn disabled={busy} data-testid="document-approve" onClick={()=>action(detail,'approve')}><Check size={15}/>Setujui & Publikasikan</Btn></>}</div></>}</Modal>
 <Modal title="Tolak Ketentuan" open={!!reject} onClose={()=>setReject(null)}><Field label="Alasan penolakan"><textarea data-testid="document-reject-reason" rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Catatan perbaikan untuk administrator..."/></Field><div className="form-actions"><Btn disabled={busy||!reason.trim()} data-testid="document-reject-confirm" onClick={()=>action(reject,'reject',reason)}>Kirim Catatan</Btn></div></Modal>
 <Modal title="Hapus draf ketentuan?" open={!!remove} onClose={()=>setRemove(null)}><p data-testid="delete-document-confirmation">Draf “{remove?.title}” akan dihapus dari daftar ketentuan.</p><div className="form-actions"><Btn secondary data-testid="document-delete-cancel" onClick={()=>setRemove(null)}>Batal</Btn><Btn className="btn-danger" disabled={busy} data-testid="document-delete-confirm" onClick={destroy}>Hapus Draf</Btn></div></Modal>
 </>;
}

function DocumentForm({initial,onClose,onSaved}){
 const [form,setForm]=useState(initial),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[id,setId]=useState(initial.id);
 const change=(key,value)=>setForm(f=>({...f,[key]:value}));
 const save=async e=>{e.preventDefault();setBusy(true);try{let docId=id;if(docId)await api.put(`/documents/${docId}`,form);else{const {data}=await api.post('/documents',form);docId=data.id;setId(docId);}if(file){const upload=new FormData();upload.append('file',file);await api.post(`/documents/${docId}/upload`,upload);}toast.success('Draf ketentuan berhasil disimpan.');onSaved();}catch{}finally{setBusy(false);}};
 return <Modal title={initial.id?'Edit Ketentuan':'Tambah Ketentuan'} open onClose={()=>!busy&&onClose()} wide><form onSubmit={save}><div className="form-grid"><Field label="Judul Ketentuan *" className="field-full"><input data-testid="document-title-input" required minLength={3} maxLength={200} value={form.title} onChange={e=>change('title',e.target.value)} placeholder="Contoh: Pedoman Penerapan APU dan PPT"/></Field><Field label="Nomor Ketentuan *"><input data-testid="document-number-input" required minLength={3} value={form.number} onChange={e=>change('number',e.target.value)} placeholder="001/SK/DIR/2026"/></Field><Field label="Kategori"><select data-testid="document-category-input" value={form.category} onChange={e=>change('category',e.target.value)}><option>Internal</option><option>Eksternal</option></select></Field><Field label="Unit Pemilik"><select data-testid="document-unit-input" value={form.unit} onChange={e=>change('unit',e.target.value)}>{units.map(u=><option key={u}>{u}</option>)}</select></Field><Field label="Versi"><input data-testid="document-version-input" required value={form.version} onChange={e=>change('version',e.target.value)}/></Field><Field label="Ringkasan Ketentuan" className="field-full"><textarea data-testid="document-description-input" rows={3} value={form.description} onChange={e=>change('description',e.target.value)} placeholder="Ringkasan isi dan ruang lingkup ketentuan..."/></Field><Field label="Berkas Dokumen" className="field-full"><div className="upload-zone"><UploadCloud size={27}/><span>{file?.name||initial.filename||'Pilih berkas ketentuan'}</span><input data-testid="document-file-input" type="file" accept=".pdf,.docx" onChange={e=>setFile(e.target.files[0])}/><small>PDF atau DOCX · Maksimal 10 MB</small></div></Field></div><div className="form-actions"><Btn type="button" secondary data-testid="document-form-cancel" onClick={onClose} disabled={busy}>Batal</Btn><Btn type="submit" data-testid="document-form-save" disabled={busy}>{busy?'Menyimpan...':'Simpan Draf'}</Btn></div></form></Modal>;
}